plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/sessions/kind-happy-wright/mnt/get_me_to_Korea/braintrust-af1-showcase"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]